name: entao_range
description: open range and close range.
version: 1.0.5
repository: https://github.com/yangentao/entao_range
homepage: https://github.com/yangentao/entao_range

environment:
  sdk: ^3.6.0
resolution: workspace

#dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
